QEMU_CFLAGS += -I$(SRC_PATH)/include

-include config-qom.mak

include $(SRC_PATH)/qapi/Makefile
common-obj-y += $(addprefix qapi/,$(qapi-obj-y))

include $(SRC_PATH)/qom/Makefile
common-obj-y += $(addprefix qom/,$(qom-obj-y))

include $(SRC_PATH)/devices/Makefile
common-obj-y += $(addprefix devices/,$(devices-obj-y))

include $(SRC_PATH)/chrdrv/Makefile
common-obj-y += $(addprefix chrdrv/,$(chrdrv-obj-y))

