target-y += ppc.o
target-y += prep.o prep_pci.o
target-y += 4xx_devs.o 4xx_pci.o 405_uc.o 405_boards.o
target-y += 440.o 440_bamboo.o
target-y += e500_pci.o e500_mpc8544ds.o
target-y += heathrow_pic.o grackle_pci.o oldworld.o
target-y += unin_pci.o newworld.o
