target-y                        := core.o qdev.o
target-$(CONFIG_IDE_PCI)        += pci.o
target-$(CONFIG_IDE_ISA)        += isa.o
target-$(CONFIG_IDE_MACIO)      += macio.o
target-$(CONFIG_IDE_MICRODRIVE) += microdrive.o
target-$(CONFIG_IDE_MMIO)       += mmio.o
