devices-obj-y += type.o plug.o plug-proptypes.o pin.o device.o
devices-obj-y += pc/i440fx.o pci_bus.o
common-obj-y += $(addprefix devices/,$(devices-obj-y))

include $(SRC_PATH)/devices/gates/Makefile
