#!/bin/bash

path=$(dirname "$0")
if test "${path}" != "." -o "${0:0:1}" = "." ; then
    helper="${path}/qemu-bridge-helper"
else
    helper="qemu-bridge-helper"
fi
echo "\"${helper}\" --bridge=qemubr0"
exit 0
