slirp-obj-$(CONFIG_SLIRP) = cksum.o if.o ip_icmp.o ip_input.o ip_output.o
slirp-obj-$(CONFIG_SLIRP) += slirp.o mbuf.o misc.o sbuf.o socket.o tcp_input.o tcp_output.o
slirp-obj-$(CONFIG_SLIRP) += tcp_subr.o tcp_timer.o udp.o bootp.o tftp.o arp_table.o
