chrdrv-obj-$(CONFIG_CHRDRV) := chrdrv.o
chrdrv-obj-$(CONFIG_CHRDRV_MEM) += memchr.o
chrdrv-obj-$(CONFIG_CHRDRV_SOCKET) += socketchr.o
chrdrv-obj-$(CONFIG_CHRDRV_TCP_SERVER) += tcpsrv.o
chrdrv-obj-$(CONFIG_CHRDRV_UNIX_SERVER) += unixsrv.o
