9pfs-obj-$(CONFIG_VIRTFS)  = virtio-9p.o
9pfs-obj-$(CONFIG_VIRTFS) += virtio-9p-local.o virtio-9p-xattr.o
9pfs-obj-$(CONFIG_VIRTFS) += virtio-9p-xattr-user.o virtio-9p-posix-acl.o
9pfs-obj-$(CONFIG_VIRTFS) += virtio-9p-coth.o cofs.o codir.o cofile.o
9pfs-obj-$(CONFIG_VIRTFS) += coxattr.o virtio-9p-synth.o
9pfs-obj-$(CONFIG_OPEN_BY_HANDLE) +=  virtio-9p-handle.o
9pfs-obj-$(CONFIG_VIRTFS) += virtio-9p-proxy.o
